### ISSUE TITLE
ArgumentException when Scrolling

### ISSUE THREAD

**Issue by Jonarw** [PropertyTools/PropertyTools#142]
To reproduce:

- Start `TreeListBoxDemo `project
- Scroll down in the TreeListBox

An ArgumentException, stating "The height can not be negative" is thrown here:
https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools.Wpf/TreeListBox/TreeListBox.cs#L733

**Comment by objorke** [comment]
are you running on .net 4.5.2 or later?

**Comment by objorke** [comment]
#38 is very similar

**Comment by Jonarw** [comment]
The `TreeListBoxDemo `uses .NET 4.5. If I change that to 4.5.2, it seems to work fine.

**Comment by objorke** [comment]
I just tested the demo, upgrading to 4.5.2 or even 4.6.2 seems not solve it on my machine.

**Comment by Jonarw** [comment]
Doesn't work for

**Comment by woodlandhunter** [comment]
It consistently crashes for me so I looked at it a bit:

There's some code in the VirtualizingStackPanel involved [here](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/VirtualizingStackPanel.cs,3789) where  `ExtendViewport()` is called with a few arguments equal to `Size.Empty` (which has a Height of `-Infinity`). 

[Later](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/VirtualizingStackPanel.cs,4653) under certain conditions one of the `-Infinity` values are used when updating a `Rect.Height` property, which fails.

Unfortunately I don't have source stepping for 4.6.2, so I'm only able to see locals and the callstack...

**Comment by objorke** [comment]
would it help to change to a lower .NET framework version?

**Comment by JosephGarrone** [comment]
I'm also encountering this bug, with .NET 4.6.2. I just put a `try...catch` around the final line in the `Insert` method for `TreeListBox` and have encountered no errors since.

```

try
{
    this.Items.Insert(index, item);
}
catch (ArgumentException ex)
{
    // Do nothing
}
```

Unsure of the ramifications,  but I haven't encountered any issues so far.

**Comment by objorke** [comment]
Closing this for now, but I hope to see a better solution :-)

**Comment by objorke** [comment]
- https://github.com/dotnet/wpf/pull/6013 (2022)
- https://github.com/dotnet/wpf/issues/7159 (2022)
- https://github.com/dotnet/wpf/issues/2854 (2020)
- https://github.com/dotnet/wpf/issues/382 (2019)
- https://learn.microsoft.com/en-us/answers/questions/587461/argumentexception-height-must-be-non-negative-from
