### ISSUE TITLE
TreeListBox DirectoryDemo not working

### ISSUE THREAD

**Issue by objorke** [PropertyTools/PropertyTools#144]
When expanding a drive node, the folders are added at the end of the tree, not under the drive node.

![image](https://cloud.githubusercontent.com/assets/439716/21741163/3363d31e-d4ce-11e6-88d3-6f9275ab31b7.png)

The DCIM folder node should be under the H: drive node

**Comment by Jonarw** [comment]
Happens in my project as well. Seems only to occur on the top two layers (at least in my case).

**Comment by Jonarw** [comment]
This line is the problem:
https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools.Wpf/TreeListBox/TreeListBox.cs#L616

This causes the next sibling on the top level not to be found.

**Comment by Jonarw** [comment]
Somewhat related: the TreeListBox also does not listen for Collection changes on the top level, while it does on the lower levels.

A fix for both issues could maybe introduce an invisible root node which contains the top level list items?

**Comment by Jonarw** [comment]
I will make a PR with some fixes I did to the `TreeListBox `- includes the ones already discussed as well as some naming issues (`HierarchySource `dp was inconsistent, which sometimes seemed to irritate the Designer). I hope it's ok to include all those in one PR...

**Comment by objorke** [comment]
Great! Yes you can include several fixes in one PR, but please create one commit for each issue - to make it easier to review.

**Comment by objorke** [comment]
It works in the latest version, but I have not checked with NuGet package. Don't think there should be any difference.
