### ISSUE TITLE
List<string> not working

### ISSUE THREAD

**Issue by verybadsoldier** [PropertyTools/PropertyTools#203]
I think there is a bug which makes it impossible to add items to a list of strings when using a PropertyGrid.

When clicking `+` to add a new item and after entering text then the text disappears as soon as you leave the input field. This is reproducible in the demo application:
![image](https://user-images.githubusercontent.com/364469/46298796-4487f480-c5a0-11e8-960c-eb1ad8fbc2f1.png)

This might be related to this issue:
https://github.com/objorke/PropertyTools/issues/155

I have read in that issue that there is a refresh problem currently which can be fixed by using observable collections. But also when switching from `List<string>` to `ObservableCollection<string>` then the issue still persists.

Please help :)

**Comment by objorke** [comment]
I think this is covered by #157
