### ISSUE TITLE
How to name the DataGridColumn‘s Header with Property's [DisplayName]Attribute?

### ISSUE THREAD

**Issue by zhanggaolei001** [PropertyTools/PropertyTools#207]
In the control "PropertyGrid"(wpf), my 'SelectedObject' has a property of 'List<ExampleItem>' ,which was displayed as a "DataGrid" control. the headers are 'ExampleItem'`s property name, Like 'Id' 、‘Name’、‘Discription’，I want to show them in Chinese，like“序号”，“姓名”,“描述” 。
I found the "PropertyGrid" was displaying their [DisplayName]Attribute, Can we do that in the datagrid when the columns were AutoGenerated? or add an event like OnAutoGeneratingColumn?

**Comment by zhanggaolei001** [comment]
OK,I found the example of CustumControlFactory, I override the CreateGridControl function, and set binding to the ControlFactory, I think it`s the right way~

**Comment by zhanggaolei001** [comment]
my code ,for someone who need it:)
` public class MyControlFactory: PropertyGridControlFactory
    {
       protected override FrameworkElement CreateGridControl(PropertyItem property)
        {
            var c = new DataGrid()
            {
                AutoGenerateColumns = true,
            };
            c.SetBinding(DataGrid.ItemsSourceProperty, property.CreateBinding());
            c.AutoGeneratingColumn += (o, e) =>
            {
                {
                    e.Column.Header = ((PropertyDescriptor)e.PropertyDescriptor).DisplayName; ;
                }
            };
            return c;
        }       
    }`
And the the xaml:
`  <Grid
                        Grid.Column="2">
                        <Grid.Resources>
                            <mdsview:MyControlFactory
                                x:Key="MyControlFactory"></mdsview:MyControlFactory>
                        </Grid.Resources>
                        <pt:PropertyGrid
                            Name="PropertyGrid"
                            ControlFactory="{Binding Source={StaticResource MyControlFactory} }"
                            SelectedObject="{Binding ElementName=TreeView,Path=SelectedItem}"></pt:PropertyGrid>
                    </Grid>
                    `

**Comment by gmkado** [comment]
> my code ,for someone who need it:)
> ` public class MyControlFactory: PropertyGridControlFactory { protected override FrameworkElement CreateGridControl(PropertyItem property) { var c = new DataGrid() { AutoGenerateColumns = true, }; c.SetBinding(DataGrid.ItemsSourceProperty, property.CreateBinding()); c.AutoGeneratingColumn += (o, e) => { { e.Column.Header = ((PropertyDescriptor)e.PropertyDescriptor).DisplayName; ; } }; return c; } }`
> And the the xaml:
> ` <Grid Grid.Column="2"> <Grid.Resources> <mdsview:MyControlFactory x:Key="MyControlFactory"></mdsview:MyControlFactory> </Grid.Resources> <pt:PropertyGrid Name="PropertyGrid" ControlFactory="{Binding Source={StaticResource MyControlFactory} }" SelectedObject="{Binding ElementName=TreeView,Path=SelectedItem}"></pt:PropertyGrid> </Grid>`

Use `System.Windows.Controls.DataGrid`, not `PropertyTools.Wpf.DataGrid`

**Comment by PFox28** [comment]
This is my very first comment on git, maybe it helps someone. I am not satisfied with the above solution, so here is mine. 

My szenario is that I have a class A which has properties that are lists containing objects of a second class B that also has properties. Even though all properties in class B have DisplayName attributes, the DataGrid does not use them as column headers. Here is my solution:

```
public class MyDataGrid : DataGrid
{
    protected override IDataGridOperator CreateOperator()
    {
        var list = this.ItemsSource;
        if (list == null)
        {
            return null;
        }

        return new MyListOperator(this);
    }
}


public class MyListOperator : ListOperator
{
    public MyListOperator(DataGrid owner) : base(owner)
    {
    }

    public override void AutoGenerateColumns()
    {
        var itemType = this.Owner.ItemsSource.GetType().GetGenericArguments().Single();

        foreach (var cd in this.GenerateColumnDefinitions(this.Owner.ItemsSource))
        {
            var pd = TypeDescriptor.GetProperties(itemType)[cd.PropertyName];
            if (pd != null)
            {
                string dname = pd.GetDisplayName();
                cd.Header = string.IsNullOrWhiteSpace(dname) ? cd.PropertyName : dname;
            }
            else
            {
                cd.Header = cd.PropertyName;
            }

            this.Owner.ColumnDefinitions.Add(cd);
        }
    }
}

public class MyControlFactory : PropertyGridControlFactory
{
    protected override FrameworkElement CreateGridControl(PropertyItem property)
    {
        var c = new MyDataGrid
        {
            CanDelete = property.ListCanRemove,
            CanInsert = property.ListCanAdd,
            InputDirection = property.InputDirection,
            IsEasyInsertByMouseEnabled = property.IsEasyInsertByMouseEnabled,
            IsEasyInsertByKeyboardEnabled = property.IsEasyInsertByKeyboardEnabled,
            AutoGenerateColumns = property.Columns.Count == 0,
            
        };
        c.SetBinding(DataGrid.ItemsSourceProperty, property.CreateBinding());
        return c;
    }
}
```


And the XAML part:

```
<Grid.Resources>
                    <local:MyControlFactory x:Key="CF"></local:MyControlFactory>
</Grid.Resources>
<pt:PropertyGrid SelectedObject="{Binding Path=InstanceOfClassA}"
                             ControlFactory="{Binding Source={StaticResource CF}}" />

```
