### ISSUE TITLE
Crash when trying to open Color Picker control

### ISSUE THREAD

**Issue by andremarques-gamedev** [PropertyTools/PropertyTools#235]
Hello,

Recently I encountered a problem when opening the color picker in a application I made.
Basically I made this app in another pc and there the build and the debug version worked just fine.

I tried to run the application and I also tried to run the debug version through the Visual Studio project and when I click in the color picker it stops responding.

The VS even throws an error saying **Managed Debugging Assistant 'ContextSwitchDeadlock'**
Saying that couldn't change from context COM 0x8e9a90 to COM 0x8e99d8.

Is there anything that I am missing here?

**Comment by objorke** [comment]
Are you using different .NET versions? Remote desktop or something like that?

**Comment by andremarques-gamedev** [comment]
Not that I am aware of in the current pc the target framework is .NET 4.6.1

**Comment by andremarques-gamedev** [comment]
I think I have found the problem in my xaml file. In the line of code above if I remove the SelectedColor property or parameter it's works just fine.

`<pt:ColorPicker x:Name="ColorPickerControl" SelectedColor="{Binding Path=Color}" Width="110" MinWidth="110" MinHeight="25" Margin="20,10,0,0" HorizontalAlignment="Left" Height="25" VerticalAlignment="Top"/>`

**Comment by andremarques-gamedev** [comment]
Ok my problem is solved, I was calling the GC.Collect() inside a function the selected color changed. That was causing me the problem, removed that now it is working like a charm. Strange that only crashed in this pc.
