### ISSUE TITLE
Not work for .net core 3 desktop app.

### ISSUE THREAD

**Issue by GF-Huang** [PropertyTools/PropertyTools#236]
![image](https://user-images.githubusercontent.com/4510984/77145307-17484280-6ac3-11ea-95ce-0d407351ee79.png)
![image](https://user-images.githubusercontent.com/4510984/77145310-18796f80-6ac3-11ea-8dfd-465483b263b1.png)

**Comment by objorke** [comment]
Version 3.0.0 does not support netcoreapp3.0, you need to use the 3.1.0 pre-release package.

This works:
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PropertyTools.Wpf" Version="3.1.0-alpha0041" />
  </ItemGroup>

</Project>
```
