### ISSUE TITLE
.NET Core package missing types/interfaces

### ISSUE THREAD

**Issue by Sybren-** [PropertyTools/PropertyTools#244]
I'm researching if our .NET Framework application can be upgraded to .NET Core.

Previously we used the .NET Framework dll with version 2011.3.0.0

I'm lookin into replacing this dll with package : https://www.nuget.org/packages/PropertyTools.Wpf/3.1.0-alpha0041

But it seems a lot of types/interfaces are missing.

Examples:

PropertyEditor
CategoryTemplateSelector
CategoryViewModel
PropertyViewModel
ILocalizationService

Have these types/interfaces been moved under a different namespace or to a different package?
Or are they removed? If so, what are the alternative options?

**Comment by objorke** [comment]
The name of the property grid is now `PropertyGrid`, architecture has also changed to use "control factory" and an "operator" objects, not view models. I think almost all functionality has been kept since v2011.
