### ISSUE TITLE
Select multiple files in PropertyGrid

### ISSUE THREAD

**Issue by tanothing** [PropertyTools/PropertyTools#246]
Hi there,
I'm using PropertyControl on WPF. I want to be able to choose multiple file and change file type to video. But I cannot file the way to do it. I try to add image property but it not work. Please guide me how to do it. Thank you!

![image](https://user-images.githubusercontent.com/22269285/89098002-17136880-d40e-11ea-97d8-58d74ae7e98c.png)

**Comment by objorke** [comment]
Multi-select is implemented on the `FilePicker` https://github.com/PropertyTools/PropertyTools/blob/develop/Source/PropertyTools.Wpf/Controls/FilePicker/FilePicker.cs#L196

Is the problem missing support in the `PropertyGrid`?

**Comment by tanothing** [comment]
Thank for your answer. The problem is: in the version has multi select property, it does not have Property Editor. Am I correct?
Anw, I resolved this issue by creating a custom dialog. Thanks again!
