### ISSUE TITLE
Paste isn't working for DataGrid

### ISSUE THREAD

**Issue by Sainyam2003** [PropertyTools/PropertyTools#269]
pasting multiple rows in DataGrid isn't working, it shows default value(s) for each row(s). The number of rows are created as per source but not the values. Paste is working fine when pasting for the second time.

**Comment by objorke** [comment]
## Steps to reproduce (1)

1.	Open `List<int>` example from data grid examples.
2.	Delete all already populated rows (i.e. data grid is empty)
3.	Paste a list of integers from an excel sheet (I had three values in list)
4.	Observe that the grid is still empty
5.	Click on ‘+’ to add new rows.  
6.	Four rows are added and all of them have zeros. (three rows for pasted values and one new row)
7.	Paste again, actual values are now pasted.

## Steps to reproduce (2)

1.	Open `ObservableCollection<double>´ example from data grid examples.
2.	Delete all already populated rows (i.e. data grid is empty)
3.	Paste a list of integers from an excel sheet (I had three values in list)
4.	Observe that the grid is filled with 0s.
5.	Paste again, actual values are now pasted.

**Comment by objorke** [comment]
It seems like `GetCellValue` returns null because the number of rows is not updated correctly.
https://github.com/PropertyTools/PropertyTools/blob/develop/Source/PropertyTools.Wpf/DataGrid/Operators/DataGridOperator.cs#L226

I think line 226-228 can be removed, as "outside bounds" is handled in the `GetItem` method.

**Comment by objorke** [comment]
The `GetItemCount` returns 0 since the collection view has not been updated. I suggest to add
`this.UpdateCollectionView();` at https://github.com/PropertyTools/PropertyTools/blob/develop/Source/PropertyTools.Wpf/DataGrid/DataGrid.cs#L1421
