### ISSUE TITLE
a question about INotifyPropertyChanged

### ISSUE THREAD

**Issue by smrcqq1** [PropertyTools/PropertyTools#320]
in this project,the auther had ever not called OnPropertyChanged,how you can do this ? please teach me!
![image](https://user-images.githubusercontent.com/74051511/225845658-91eb406c-4e3f-43a9-8cb2-9aa976512684.png)

**Comment by mpartipilo** [comment]
It's from FodyWeaver using the Property Changed plugin.

It automates the dispatch of the OnPropertyChanged event.
