### ISSUE TITLE
Cells in the DataGrid do not bind correctly to a list of arrays

### ISSUE THREAD

**Issue by kjellt** [PropertyTools/PropertyTools#343]
The data context returned by the DataGridOperator is inconsistent with the binding expression returned by the ListListOperator when the item source is a list of lists.

**Comment by objorke** [comment]
I understand this can be reproduced with a `List<object>` - where the type definition cannot indicate that it is a list of lists
```
            this.ItemsSource = new List<object> {
                new List<int> { 1,2,3},
                new List<int> { 4,5,6}
            };
```
