### ISSUE TITLE
Enhance RadioButton Control with Individual Button Enable/Disable Capability

### ISSUE THREAD

**Issue by deeora** [PropertyTools/PropertyTools#349]
### Context:

Currently, our application lacks a standardized method to enable or disable individual RadioButtons within a group based on specific conditions or attributes.

### Feature Description:

Introduce the OptionEnableAttribute:
- Enables developers to specify conditions on enum values to control whether a RadioButton should be enabled or disabled.

### Example Usage:

```csharp
public enum TestEnum
{
    Red,
    [OptionEnable("EnableGreenColorOption")]
    Green,
    Blue
}
```

![radiobutton](https://github.com/user-attachments/assets/5b4fb8fc-70e8-4722-b639-59b2350d58fb)

**Comment by objorke** [comment]
Rename to `OptionEnableByAttribute` to be consistent with the other attributes. I see this is already implemented in the PR!
