### ISSUE TITLE
Should Use Language or CurrentUICulture instead of CurrentCulture for converter

### ISSUE THREAD

**Issue by yll690** [PropertyTools/PropertyTools#352]
For example: https://github.com/PropertyTools/PropertyTools/blob/957bb516f6d34c457674cb05c0aeec6dd54c6463/Source/PropertyTools.Wpf/Controls/RadioButtonList/RadioButtonList.cs#L290-L294

In wpf it use `FrameworkElement.Language` to provide culture to converters. However it need to set separately. The CurrentUICulture is more convenient. 
The CurrentCulture is used to `determines the default format for dates, times, numbers, and currency values, the sorting order of text, casing conventions, and string comparisons.` (https://learn.microsoft.com/zh-cn/dotnet/fundamentals/runtime-libraries/system-globalization-cultureinfo-currentculture), not to determines the text string content.

**Comment by objorke** [comment]
Thanks for the explanation! Please create a PR!
