### ISSUE TITLE
ItemsBag Property Descriptor should not suppress the property change notifications.

### ISSUE THREAD

**Issue by deeora** [PropertyTools/PropertyTools#353]
ItemsBag Property Descriptor should not supress the propetry change notifications

The current behaviour is that the ItemsBag Property Descriptor suppresses all change notifications, significantly impacting the display of WPF components.

A WPF model's property may raise different RaisePropertyChanged for the other properties when it receives an update value. 

For example, the model below has a property _IsChecked_, which raises RaisePropertyChanged events for _ShowColor_ in addition to for itself. The _ShowColor_ controls the display behaviour of the Color property. 

The ItemsBag Property Descriptor's current behaviour prevents RaisePropertyChanged for the _ShowColor_ property, which stops the Color item from being displayed in ItemsBag.

```C#
public enum Colors { Red, Green, Blue }

public class Model : INotifyPropertyChanged
{
    public bool ShowColor => IsChecked;

    private bool isChecked;

    public bool IsChecked
    {
        get
        {
            return this.isChecked;
        }
        set
        {
            if (this.isChecked != value)
            {
                this.isChecked = value;
                RaisePropertyChanged(nameof(IsChecked));
                RaisePropertyChanged(nameof(ShowColor));
            }
        }
    }

    private Colors color;

    [VisibleBy(nameof(ShowColor))]
    public Colors Color
    {
        get
        {
            return this.color;
        }
        set
        {
            this.color = value;
            RaisePropertyChanged("Color");
        }
    }

    public event PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string property)
    {
        Debug.WriteLine("Model.RaisePropertyChanged on " + property);

        var handler = PropertyChanged;
        if (handler != null)
        {
            handler(this, new PropertyChangedEventArgs(property));
        }
    }
}
````

This is the behaviour what can be seen with the ItemsBag example:
![itemsbag-suppresses](https://github.com/user-attachments/assets/c70fcb76-2073-443a-805d-422e9d07a326)

The excepted behaviour is:
![itemsbag-fix](https://github.com/user-attachments/assets/eca49a5a-b466-4e78-ae68-3b7957c99f22)

**Comment by objorke** [comment]
thanks for including the animations!
