### ISSUE TITLE
How to set a PropertyItem to readonly?

### ISSUE THREAD

**Issue by mobarhani** [PropertyTools/PropertyTools#359]
Hi
I use from PropertyGrid for displaying details of selected item in datagrid (WPF) which ItemsSource is binded to the list of objects. How can I set a  propertyItem to readonly?

**Comment by deeora** [comment]
@mobarhani We are using like this 

`<Property Name="ParentLengthOfTransient" Header="Length of transient" IsReadOnly="true">The transient period assigned to this run.</Property>`

**Comment by mobarhani** [comment]
> @mobarhani We are using like this
> 
> `<Property Name="ParentLengthOfTransient" Header="Length of transient" IsReadOnly="true">The transient period assigned to this run.</Property>`

I use propertyGrid like this:

<pt:PropertyGrid SelectedObject="{Binding MySelectedItem}" >
 </pt:PropertyGrid>

The properties are created automatically.

**Comment by deeora** [comment]
@mobarhani , right. I suggest you to see the below example and if possible try to run:
 https://github.com/PropertyTools/PropertyTools/blob/ece2ad84cb8ad87f764395470dbc7eebf9fdf13e/Source/Examples/PropertyGrid/PropertyGridDemo/Examples/ReadOnlyAttributeExample.cs#L10

![image](https://github.com/user-attachments/assets/64291fdb-bffd-4a89-b4e1-1a8587aa6bdf)

**Comment by mobarhani** [comment]
@deeora , Thanks. This example was helpful.
