### ISSUE TITLE
Error: Could not find file or assembly

### ISSUE THREAD

**Issue by HartlD** [PropertyTools/PropertyTools#54]
I will get this error of my propertyGrid:
Error   1   Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. Das System kann die angegebene Datei nicht finden.

**Comment by objorke** [comment]
This sounds like a portable class library issue. Is your Visual Studio installation up to date?

**Comment by aldinei-sampaio** [comment]
I have the same problem here and I am sure my VS is updated.

**Comment by HartlD** [comment]
Hello, Yes my VS2013 is up to date.

**Comment by objorke** [comment]
Are you using the latest NuGet package? What .NET version and operating system?
Are the example projects working? 
Can you provide a simple example project that reproduces the issue?

**Comment by aldinei-sampaio** [comment]
The problems seems to be VS IDE debugging related. Here is how I reproduce it:

1) Open the solution (the problem happens with both NET40 and NET45)
2) Set the project PropertyGridDemo_NET40 or PropertyGridDemo_NET45 as startup project
3) Click on Start
4) On the "PropertyGrid" menu, choose "Show declared only"

However, if I go to the bin\debug folder and run the PropertyGridDemo.exe, or if i choose "Start without debug" on VS, it runs fine without crashing.

**Comment by aldinei-sampaio** [comment]
I am using Windows 8.1 / VS 2013 Community Edition / All NuGet packages updated to most recent.

BTW, there is a compilation error on project UndoRedoDemo_NET40 / UndoRedoDemo_NET45 with the most recent version of Caliburn Micro. "Bootstrapper" class not found on AppBootstrapper.cs, line 20.

**Comment by aldinei-sampaio** [comment]
OMG, sorry, I had been posting in the wrong thread.

**Comment by ChristianPerner** [comment]
VS2013 Update 4
PropertyTools 2015.1.61
Above error message in this code within line containing TabVisibility:
![propertytoolsxml](https://cloud.githubusercontent.com/assets/12427711/7609418/f91e8196-f972-11e4-9950-c4cb642a3138.PNG)
Problem is only during design-time, not run-time.
![propertytoolserror](https://cloud.githubusercontent.com/assets/12427711/7609377/b7fb4c62-f972-11e4-9954-df5839c75635.PNG)

**Comment by GF-Huang** [comment]
Same issue, #236
