### ISSUE TITLE
FilePicker.Browse fails when FilePath does not exist.

### ISSUE THREAD

**Issue by AnalyticRoom** [PropertyTools/PropertyTools#65]
Starting the FilePicker.Browse with a FilePath for a file that does not exist, throws exception.
Expected behaviour would be to fall back on the path without the non-existing file (if that one exists, that is:-)
Example:
If "C:\herbert.txt" does not exists FilePicker should show "C:\"

**Comment by objorke** [comment]
Cannot reproduce this..
What if the `FilePath = "C:\herbert\herbert.txt"`? Should it show "C:\"?
And what if the `FilePath = "H:\herbert\herbert.txt"` and there is no H drive?

**Comment by objorke** [comment]
Cannot reproduce in current version.
